- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: nodes
  become: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars['master'].join_command }} > node-join-cluster.txt 2>&1  || { cat node-join-cluster.txt; rm -f node-join-cluster.txt; false; }"
      args:
        chdir: $HOME
        creates: node-join-cluster.txt
